/***
 * THIS FILE IS AUTOMATICALLY GENERATED
 * Do not edit this file. It will be overwritten when the configure script is run.
 ***/

#ifndef CHAMPSIM_CONSTANTS_H
#define CHAMPSIM_CONSTANTS_H
#include "util.h"
#define BLOCK_SIZE 64ul
#define LOG2_BLOCK_SIZE lg2(BLOCK_SIZE)
#define PAGE_SIZE 4096ul
#define LOG2_PAGE_SIZE lg2(PAGE_SIZE)
#define STAT_PRINTING_PERIOD 10000000ul
#define NUM_CPUS 8ul
#define NUM_CACHES 49u
#define ALLOW_PAM 0
#define PAM_TH 50
#define NUM_OPERABLES 66u
#define DRAM_IO_FREQ 2400ul
#define CXL_MODE 0ul
#define DRAM_CHANNELS 2ul
#define DRAM_RANKS 2ul
#define DRAM_BANKS 32ul
#define DRAM_ROWS 262144ul
#define DRAM_COLUMNS 2048ul
#define DRAM_CHANNEL_WIDTH 4ul
#define DRAM_WQ_SIZE 512ul
#define DRAM_RQ_SIZE 512ul
#define tRP_DRAM_NANOSECONDS 16.6
#define tRCD_DRAM_NANOSECONDS 16.6
#define tCAS_DRAM_NANOSECONDS 16.6
#define DBUS_TURN_AROUND_NANOSECONDS 7.5
#endif
