CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TOOL_ROOTS := champsim_tracer_w_magic icount_w_magic champsim_tracer_w_magic_killwhendone

include $(CONFIG_ROOT)/makefile.config
include $(TOOLS_ROOT)/Config/makefile.default.rules

